// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 09 Jan 2018 01:37:44 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

#include <GLES2/gl2.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

