// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 09 Jan 2018 01:37:44 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

/*
Package gles2 provides Go bindings for the OpenGL ES v2 API.
*/
package gles2
