// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 09 Jan 2018 01:37:44 CST.
// By https://git.io/c-for-go. DO NOT EDIT.

package gles2

/*
#cgo CFLAGS: -I/opt/vc/include
#cgo LDFLAGS: -L/opt/vc/lib -lGLESv2
#include <GLES2/gl2.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// Void type as declared in GLES2/gl2.h:48
type Void [0]byte

// Char type as declared in GLES2/gl2.h:49
type Char byte

// Enum type as declared in GLES2/gl2.h:50
type Enum uint32

// Boolean type as declared in GLES2/gl2.h:51
type Boolean byte

// Bitfield type as declared in GLES2/gl2.h:52
type Bitfield uint32

// Byte type as declared in GLES2/gl2.h:53
type Byte byte

// Short type as declared in GLES2/gl2.h:54
type Short int16

// Int type as declared in GLES2/gl2.h:55
type Int int32

// Sizei type as declared in GLES2/gl2.h:56
type Sizei int32

// Ubyte type as declared in GLES2/gl2.h:57
type Ubyte byte

// Ushort type as declared in GLES2/gl2.h:58
type Ushort uint16

// Uint type as declared in GLES2/gl2.h:59
type Uint uint32

// Float type as declared in GLES2/gl2.h:60
type Float float32

// Clampf type as declared in GLES2/gl2.h:61
type Clampf float32

// Fixed type as declared in GLES2/gl2.h:62
type Fixed int32

// Intptr type as declared in GLES2/gl2.h:65
type Intptr int

// Sizeiptr type as declared in GLES2/gl2.h:66
type Sizeiptr int
